
esphome:
  name: esptest2
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  fast_connect: true
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
deep_sleep:
  run_duration: 30s
  sleep_duration: 30s