esphome:
  name: scarecrow
  platform: ESP32
  board: esp32doit-devkit-v1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: scarecrow
            level: !lambda 'return level / 100.0;'

ota:

switch:
  - platform: template
    name: "Motion Detected Switch"
    id: template_swi
    turn_on_action:
      then:
      - script.execute: move_scarecrow      
    
# Example configuration entry
servo:
  - id: scarecrow
    output: pwm_output

# Example output platform
# On ESP32, use ledc output
output:
  - platform: ledc
    id: pwm_output
    pin: GPIO15
    frequency: 50 Hz
    
# Script to move the servo up and down
script:
  - id: move_scarecrow
    then:
      - lambda: |-
          uint min = 0;
          uint max = 100;
          float value = min + ( std::rand() % ( max - min + 1 ));
          for(uint i = 0; i<10; i++)
          {
            value = (float)(min + ( std::rand() % ( max - min + 1 )));
            if((i%2)==0){
              value *= -1.0; 
            }
            id(scarecrow).write(value / 100.0);
            delay(600);
          }
          id(scarecrow).write(1.0);
          delay(200);
          id(scarecrow).detach();
          
          



