esphome:
  name: yellowsubmarine
  platform: ESP32
  board: node32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return level / 100.0;'

ota:

# Enable Bluethooth BLE Tracker
esp32_ble_tracker:

# Example configuration entry
i2c:
  sda: 21
  scl: 22
  scan: True
  
web_server:
  port: 80

ads1115:
  - address: 0x48
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 20s
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    update_interval: 20s 
    name: "Pflanze 1"
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
    - lambda: return roundf(x*100);
    - calibrate_linear:
        - 154.00000 -> 100
        - 280.00000 -> 0
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    update_interval: 20s 
    name: "Pflanze 2"
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
    - lambda: return roundf(x*100);
    - calibrate_linear:
        - 146.00000 -> 100
        - 280.00000 -> 0
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    update_interval: 30s 
    name: "Pflanze 3"
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
    - lambda: return roundf(x*100);
    - calibrate_linear:
        - 152.00000 -> 100
        - 282.00000 -> 0
  - platform: xiaomi_xmtzc0xhm
    mac_address: 0C:95:41:CC:0D:F1
    weight:
      name: "MiScale Gewicht"
    impedance:
      name: "MiScale Impedance"
# Example configuration entry
servo:
  - id: my_servo
    output: pwm_output
    
# Example output platform
# On ESP32, use ledc output
output:
  - platform: ledc
    id: pwm_output
    pin: GPIO25
    frequency: 50 Hz