esphome:
  name: yellowsubmarine
  platform: ESP32
  board: node32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 172.18.1.11
    # Set this to the IP address of the router. Often ends with .1
    gateway: 172.18.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
i2c:
  sda: 21
  scl: 22
  scan: True

ads1115:
  - address: 0x48
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 20s
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    update_interval: 20s 
    name: "Pflanze 1"
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
    - lambda: return roundf(x*100);
    - calibrate_linear:
        - 154.00000 -> 100
        - 280.00000 -> 0
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    update_interval: 20s 
    name: "Pflanze 2"
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
    - lambda: return roundf(x*100);
    - calibrate_linear:
        - 146.00000 -> 100
        - 280.00000 -> 0
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    update_interval: 30s 
    name: "Pflanze 3"
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
    - lambda: return roundf(x*100);
    - calibrate_linear:
        - 152.00000 -> 100
        - 282.00000 -> 0